name = "friendly_crimson_deer-8a81"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "friendly_crimson_deer-8a81_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "friendly_crimson_deer-8a81.wasm"
command = "npm run build:release"
